In [1]:
import pandas as pd
import numpy as np
import pickle
from census import Census
import json

In [2]:
with open('../data/census_dict.pkl', 'rb') as f:
    census_dict = pickle.load(f)

In [3]:
# adding table on vehicle ownership to dictionary
with open('../data/census_key.json') as fi:
    credentials = json.load(fi)
    
api_key = credentials['api_key']

c = Census(api_key)

no_cars_2020 = c.acs5.zipcode(('NAME', 'group(B08201)'), zcta = Census.ALL, state = 47)

census_dict['group(B08201)'] = no_cars_2020

In [4]:
test = pd.DataFrame(census_dict['group(B25045)'])

In [5]:
test

,NAME,B25045_001E,B25045_001EA,B25045_001M,B25045_001MA,B25045_002E,B25045_002EA,B25045_002M,B25045_002MA,B25045_003E,...,B25045_018EA,B25045_018M,B25045_018MA,B25045_019E,B25045_019EA,B25045_019M,B25045_019MA,GEO_ID,state,zip code tabulation area
0,ZCTA5 53563,4282.0,None,195.0,None,3242.0,None,221.0,None,25.0,...,None,116.0,None,105.0,None,67.0,None,8600000US53563,55,53563
1,ZCTA5 53588,1782.0,None,81.0,None,1381.0,None,83.0,None,19.0,...,None,54.0,None,69.0,None,22.0,None,8600000US53588,55,53588
2,ZCTA5 53589,7925.0,None,211.0,None,6102.0,None,252.0,None,37.0,...,None,188.0,None,302.0,None,99.0,None,8600000US53589,55,53589
3,ZCTA5 53713,10129.0,None,490.0,None,2713.0,None,296.0,None,43.0,...,None,409.0,None,206.0,None,100.0,None,8600000US53713,55,53713
4,ZCTA5 53717,6127.0,None,202.0,None,3079.0,None,197.0,None,22.0,...,None,231.0,None,296.0,None,89.0,None,8600000US53717,55,53717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33115,ZCTA5 15201,6194.0,None,205.0,None,3442.0,None,228.0,None,358.0,...,None,123.0,None,162.0,None,62.0,None,8600000US15201,42,15201
33116,ZCTA5 15636,1423.0,None,133.0,None,1313.0,None,138.0,None,0.0,...,None,38.0,None,15.0,None,24.0,None,8600000US15636,42,15636
33117,ZCTA5 15696,188.0,None,91.0,None,156.0,None,89.0,None,4.0,...,None,15.0,None,3.0,None,4.0,None,8600000US15696,42,15696
33118,ZCTA5 15035,987.0,None,56.0,None,612.0,None,72.0,None,29.0,...,None,51.0,None,57.0,None,29.0,None,8600000US15035,42,15035
33119,ZCTA5 15222,2526.0,None,160.0,None,453.0,None,87.0,None,65.0,...,None,116.0,None,60.0,None,40.0,None,8600000US15222,42,15222

In [6]:
test[test['state'] == '47']

,NAME,B25045_001E,B25045_001EA,B25045_001M,B25045_001MA,B25045_002E,B25045_002EA,B25045_002M,B25045_002MA,B25045_003E,...,B25045_018EA,B25045_018M,B25045_018MA,B25045_019E,B25045_019EA,B25045_019M,B25045_019MA,GEO_ID,state,zip code tabulation area
4672,ZCTA5 38359,167.0,None,38.0,None,133.0,None,37.0,None,5.0,...,None,19.0,None,6.0,None,5.0,None,8600000US38359,47,38359
5344,ZCTA5 37330,2930.0,None,229.0,None,2424.0,None,238.0,None,95.0,...,None,100.0,None,73.0,None,53.0,None,8600000US37330,47,37330
5345,ZCTA5 37379,11151.0,None,426.0,None,9183.0,None,343.0,None,211.0,...,None,239.0,None,196.0,None,85.0,None,8600000US37379,47,37379
5346,ZCTA5 37415,10804.0,None,460.0,None,6151.0,None,424.0,None,256.0,...,None,279.0,None,547.0,None,153.0,None,8600000US37415,47,37415
5347,ZCTA5 38030,215.0,None,91.0,None,83.0,None,55.0,None,0.0,...,None,11.0,None,0.0,None,12.0,None,8600000US38030,47,38030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30722,ZCTA5 37185,3351.0,None,227.0,None,2568.0,None,210.0,None,77.0,...,None,157.0,None,126.0,None,55.0,None,8600000US37185,47,37185
30723,ZCTA5 37191,1404.0,None,184.0,None,1162.0,None,180.0,None,0.0,...,None,77.0,None,18.0,None,28.0,None,8600000US37191,47,37191
30724,ZCTA5 37209,15576.0,None,492.0,None,7245.0,None,422.0,None,132.0,...,None,367.0,None,321.0,None,121.0,None,8600000US37209,47,37209
30725,ZCTA5 37217,12857.0,None,404.0,None,5325.0,None,358.0,None,83.0,...,None,388.0,None,348.0,None,110.0,None,8600000US37217,47,37217
30726,ZCTA5 37219,811.0,None,202.0,None,233.0,None,128.0,None,0.0,...,None,126.0,None,17.0,None,28.0,None,8600000US37219,47,37219

In [7]:
census_tables = [
    'group(B25045)',
    'group(B25046)',
    'group(DP05)',
    'group(S0102)',
    'group(S0103)',
    'group(S1701)',
    'group(S1703)',
    'group(S1810)',
    'group(S1811)',
    'group(S1903)',
    'group(S2701)',
    'group(S2702)',
    'group(B01003)',
    'group(B02001)',
    'group(B09010)',
    'group(B09020)',
    'group(B08201)'
]

In [9]:
pd.Series(census_tables[0]).str.extract('.*\((.*)\).*')[0][0]

'B25045'

In [19]:
for table in census_tables:
    globals()[pd.Series(table).str.extract('.*\((.*)\).*')[0][0]] = pd.DataFrame(census_dict[table])

In [18]:
B25046 =  B25046[B25046['state'] == '47']

In [20]:
df_list = [
    'B25045',
    'B25046',
    'DP05',
    'S0102',
    'S0103',
    'S1701',
    'S1703',
    'S1810',
    'S1811',
    'S1903',
    'S2701',
    'S2702',
    'B01003',
    'B09010',
    'B09020',
    'B08201'
]

In [22]:
for df in df_list:
    df = df[df['state'] == '47']

TypeError: string indices must be integers